#if WITH_DEV_AUTOMATION_TESTS

#include "Misc/AutomationTest.h"

#include "AssetRegistry/AssetRegistryModule.h"
#include "AssetRegistry/IAssetRegistry.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "Engine/Blueprint.h"
#include "Modules/ModuleManager.h"

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FGridEditorCppClean03BlueprintLegacyReferenceAuditTest,
	"Grimrock.CppCleanup.CPP_CLEAN03.BlueprintLegacyReferences",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FGridEditorCppClean03BlueprintLegacyReferenceAuditTest::RunTest(const FString& Parameters)
{
	(void)Parameters;

	FAssetRegistryModule& AssetRegistryModule = FModuleManager::LoadModuleChecked<FAssetRegistryModule>(TEXT("AssetRegistry"));
	IAssetRegistry& AssetRegistry = AssetRegistryModule.Get();
	AssetRegistry.SearchAllAssets(true);

	FARFilter Filter;
	Filter.PackagePaths.Add(FName(TEXT("/Game/GrimrockPrototype")));
	Filter.ClassPaths.Add(UBlueprint::StaticClass()->GetClassPathName());
	Filter.bRecursivePaths = true;
	Filter.bRecursiveClasses = true;

	TArray<FAssetData> BlueprintAssets;
	AssetRegistry.GetAssets(Filter, BlueprintAssets);
	BlueprintAssets.Sort(
		[](const FAssetData& Left, const FAssetData& Right)
		{
			return Left.PackageName.ToString() < Right.PackageName.ToString();
		});

	TArray<FString> LegacyReferences;
	int32 LoadedBlueprintCount = 0;

	auto ContainsLegacyEnumValue = [](const FString& Value)
	{
		return Value.Contains(TEXT("ExplicitlyRejected"), ESearchCase::CaseSensitive);
	};

	for (const FAssetData& BlueprintAssetData : BlueprintAssets)
	{
		UBlueprint* Blueprint = Cast<UBlueprint>(BlueprintAssetData.GetAsset());
		if (!Blueprint)
		{
			AddError(FString::Printf(
				TEXT("CPP-CLEAN03 Blueprint audit could not load %s."), *BlueprintAssetData.PackageName.ToString()));
			continue;
		}

		++LoadedBlueprintCount;

		for (const FBPVariableDescription& Variable : Blueprint->NewVariables)
		{
			if (ContainsLegacyEnumValue(Variable.DefaultValue))
			{
				LegacyReferences.Add(FString::Printf(
					TEXT("%s :: Variable=%s :: DefaultValue=%s"),
					*BlueprintAssetData.PackageName.ToString(),
					*Variable.VarName.ToString(),
					*Variable.DefaultValue));
			}
		}

		TArray<UEdGraph*> Graphs;
		Graphs.Append(Blueprint->UbergraphPages);
		Graphs.Append(Blueprint->FunctionGraphs);
		Graphs.Append(Blueprint->MacroGraphs);
		Graphs.Append(Blueprint->DelegateSignatureGraphs);

		for (const UEdGraph* Graph : Graphs)
		{
			if (!Graph)
			{
				continue;
			}

			for (const UEdGraphNode* Node : Graph->Nodes)
			{
				if (!Node)
				{
					continue;
				}

				for (const UEdGraphPin* Pin : Node->Pins)
				{
					if (!Pin)
					{
						continue;
					}

					if (ContainsLegacyEnumValue(Pin->DefaultValue) || ContainsLegacyEnumValue(Pin->AutogeneratedDefaultValue))
					{
						LegacyReferences.Add(FString::Printf(
							TEXT("%s :: Graph=%s :: Node=%s :: Pin=%s :: Default=%s :: AutoDefault=%s"),
							*BlueprintAssetData.PackageName.ToString(),
							*GetNameSafe(Graph),
							*GetNameSafe(Node),
							*Pin->PinName.ToString(),
							*Pin->DefaultValue,
							*Pin->AutogeneratedDefaultValue));
					}
				}
			}
		}
	}

	TestEqual(TEXT("Every discovered Blueprint can be loaded"), LoadedBlueprintCount, BlueprintAssets.Num());

	for (const FString& Reference : LegacyReferences)
	{
		AddError(FString::Printf(TEXT("CPP-CLEAN03 ExplicitlyRejected Blueprint reference remains: %s"), *Reference));
	}

	TestEqual(TEXT("No Blueprint serializes the removed ExplicitlyRejected enum value"), LegacyReferences.Num(), 0);
	return LegacyReferences.IsEmpty() && LoadedBlueprintCount == BlueprintAssets.Num();
}

#endif // WITH_DEV_AUTOMATION_TESTS
